version: "3"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    command: "npm run start:legacy"
    ports:
      - "8080:8080"
    volumes:
      - ./express/index.html:/home/frontend/express/index.html
    networks:
      default:

# volumes:
#   frontend:
